### ISSUE TITLE
ModuleNotFoundError: No module named 'models.psroi_pooling._ext.psroi_pooling._psroi_pooling

### ISSUE THREAD

**Issue by QxGeng** [vikarthikeyan/Face-R-FCN#3]
ModuleNotFoundError: No module named 'models.psroi_pooling._ext.psroi_pooling._psroi_pooling

**Comment by CodexForster** [comment]
Just to confirm, (I have pytorch 0.4.1 and CUDA 9.2) and I got the following error:

> ImportError: /face-r-fcn_cu92/models/psroi_pooling/_ext/psroi_pooling/_psroi_pooling.so: undefined symbol: __cudaPopCallConfiguration.

After going through issues on other repos, I tried using pytorch 0.4.1 on CUDA 9.0 and this error did not show up again.
But when I run training.py using CUDA 9.0, I get this error: #4.

Let me know what can I do.
